# Generated by Django 4.2.2 on 2023-07-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_categ_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
