# Generated by Django 4.2.2 on 2023-07-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categ',
            new_name='catego',
        ),
    ]
