# Generated by Django 4.2.2 on 2023-08-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
