# Generated by Django 4.2.2 on 2023-08-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=10),
        ),
    ]
